/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import "fmt"

func fibo(topNum int) int {
    a := 1
    b := 1
    c := 0
    sum := 0

    for b < topNum {
        c = a + b
        sum += c
        a =  b + c
        b =  c + a
    }
    return sum
}

func main() {
    topNum := 4000000
    fmt.Println(fibo(topNum))
}